// Code generated by protoc-gen-go. DO NOT EDIT.
// source: RPC.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RPC_NodeType int32

const (
	RPC_OWNER RPC_NodeType = 0
	RPC_NODE  RPC_NodeType = 1
)

var RPC_NodeType_name = map[int32]string{
	0: "OWNER",
	1: "NODE",
}

var RPC_NodeType_value = map[string]int32{
	"OWNER": 0,
	"NODE":  1,
}

func (x RPC_NodeType) String() string {
	return proto.EnumName(RPC_NodeType_name, int32(x))
}

func (RPC_NodeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_438fa73ead152342, []int{0, 0}
}

type RPC_RPCType int32

const (
	RPC_PING_REQ       RPC_RPCType = 0
	RPC_PING_RES       RPC_RPCType = 1
	RPC_STORE_REQ      RPC_RPCType = 2
	RPC_STORE_RES      RPC_RPCType = 3
	RPC_FIND_NODE_REQ  RPC_RPCType = 4
	RPC_FIND_NODE_RES  RPC_RPCType = 5
	RPC_FIND_VALUE_REQ RPC_RPCType = 6
	RPC_FIND_VALUE_RES RPC_RPCType = 7
)

var RPC_RPCType_name = map[int32]string{
	0: "PING_REQ",
	1: "PING_RES",
	2: "STORE_REQ",
	3: "STORE_RES",
	4: "FIND_NODE_REQ",
	5: "FIND_NODE_RES",
	6: "FIND_VALUE_REQ",
	7: "FIND_VALUE_RES",
}

var RPC_RPCType_value = map[string]int32{
	"PING_REQ":       0,
	"PING_RES":       1,
	"STORE_REQ":      2,
	"STORE_RES":      3,
	"FIND_NODE_REQ":  4,
	"FIND_NODE_RES":  5,
	"FIND_VALUE_REQ": 6,
	"FIND_VALUE_RES": 7,
}

func (x RPC_RPCType) String() string {
	return proto.EnumName(RPC_RPCType_name, int32(x))
}

func (RPC_RPCType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_438fa73ead152342, []int{0, 1}
}

type RPC struct {
	RpcType              RPC_RPCType    `protobuf:"varint,1,opt,name=rpc_type,json=rpcType,proto3,enum=main.RPC_RPCType" json:"rpc_type,omitempty"`
	Ser                  int32          `protobuf:"varint,2,opt,name=ser,proto3" json:"ser,omitempty"`
	SenderId             []byte         `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Value                []byte         `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	NodeType             RPC_NodeType   `protobuf:"varint,5,opt,name=node_type,json=nodeType,proto3,enum=main.RPC_NodeType" json:"node_type,omitempty"`
	LookupId             []byte         `protobuf:"bytes,6,opt,name=lookup_id,json=lookupId,proto3" json:"lookup_id,omitempty"`
	SenderIp             string         `protobuf:"bytes,7,opt,name=sender_ip,json=senderIp,proto3" json:"sender_ip,omitempty"`
	OwnerIp              string         `protobuf:"bytes,8,opt,name=owner_ip,json=ownerIp,proto3" json:"owner_ip,omitempty"`
	Klist                []*RPCKnearest `protobuf:"bytes,9,rep,name=klist,proto3" json:"klist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RPC) Reset()         { *m = RPC{} }
func (m *RPC) String() string { return proto.CompactTextString(m) }
func (*RPC) ProtoMessage()    {}
func (*RPC) Descriptor() ([]byte, []int) {
	return fileDescriptor_438fa73ead152342, []int{0}
}

func (m *RPC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPC.Unmarshal(m, b)
}
func (m *RPC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPC.Marshal(b, m, deterministic)
}
func (m *RPC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPC.Merge(m, src)
}
func (m *RPC) XXX_Size() int {
	return xxx_messageInfo_RPC.Size(m)
}
func (m *RPC) XXX_DiscardUnknown() {
	xxx_messageInfo_RPC.DiscardUnknown(m)
}

var xxx_messageInfo_RPC proto.InternalMessageInfo

func (m *RPC) GetRpcType() RPC_RPCType {
	if m != nil {
		return m.RpcType
	}
	return RPC_PING_REQ
}

func (m *RPC) GetSer() int32 {
	if m != nil {
		return m.Ser
	}
	return 0
}

func (m *RPC) GetSenderId() []byte {
	if m != nil {
		return m.SenderId
	}
	return nil
}

func (m *RPC) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *RPC) GetNodeType() RPC_NodeType {
	if m != nil {
		return m.NodeType
	}
	return RPC_OWNER
}

func (m *RPC) GetLookupId() []byte {
	if m != nil {
		return m.LookupId
	}
	return nil
}

func (m *RPC) GetSenderIp() string {
	if m != nil {
		return m.SenderIp
	}
	return ""
}

func (m *RPC) GetOwnerIp() string {
	if m != nil {
		return m.OwnerIp
	}
	return ""
}

func (m *RPC) GetKlist() []*RPCKnearest {
	if m != nil {
		return m.Klist
	}
	return nil
}

type RPCKnearest struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip                   []byte   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCKnearest) Reset()         { *m = RPCKnearest{} }
func (m *RPCKnearest) String() string { return proto.CompactTextString(m) }
func (*RPCKnearest) ProtoMessage()    {}
func (*RPCKnearest) Descriptor() ([]byte, []int) {
	return fileDescriptor_438fa73ead152342, []int{0, 0}
}

func (m *RPCKnearest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCKnearest.Unmarshal(m, b)
}
func (m *RPCKnearest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCKnearest.Marshal(b, m, deterministic)
}
func (m *RPCKnearest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCKnearest.Merge(m, src)
}
func (m *RPCKnearest) XXX_Size() int {
	return xxx_messageInfo_RPCKnearest.Size(m)
}
func (m *RPCKnearest) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCKnearest.DiscardUnknown(m)
}

var xxx_messageInfo_RPCKnearest proto.InternalMessageInfo

func (m *RPCKnearest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *RPCKnearest) GetIp() []byte {
	if m != nil {
		return m.Ip
	}
	return nil
}

func init() {
	proto.RegisterType((*RPC)(nil), "main.RPC")
	proto.RegisterType((*RPCKnearest)(nil), "main.RPC.knearest")
	proto.RegisterEnum("main.RPC_NodeType", RPC_NodeType_name, RPC_NodeType_value)
	proto.RegisterEnum("main.RPC_RPCType", RPC_RPCType_name, RPC_RPCType_value)
}

func init() { proto.RegisterFile("RPC.proto", fileDescriptor_438fa73ead152342) }

var fileDescriptor_438fa73ead152342 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0x4d, 0xcf, 0x93, 0x40,
	0x10, 0xc7, 0xbb, 0xbc, 0x94, 0x65, 0x6c, 0x9b, 0xed, 0xc4, 0x03, 0xea, 0x41, 0xd2, 0x13, 0x31,
	0xa6, 0x26, 0xfa, 0x09, 0x4c, 0x8b, 0x86, 0xc4, 0x50, 0x5c, 0xaa, 0x1e, 0x49, 0xed, 0xee, 0x81,
	0xb4, 0xc2, 0x06, 0xa8, 0xa6, 0x1f, 0xc1, 0xa3, 0xdf, 0xd8, 0xec, 0x6e, 0xab, 0xe4, 0x79, 0x6e,
	0xf3, 0x7f, 0x81, 0xdf, 0x30, 0x01, 0x42, 0x5e, 0x6c, 0xd6, 0xaa, 0x6b, 0x87, 0x16, 0xbd, 0x1f,
	0x87, 0xba, 0x59, 0xfd, 0xf6, 0xc0, 0xe5, 0xc5, 0x06, 0x5f, 0x03, 0xed, 0xd4, 0xb1, 0x1a, 0xae,
	0x4a, 0x46, 0x24, 0x26, 0xc9, 0xe2, 0xed, 0x72, 0xad, 0x0b, 0x6b, 0xfd, 0x00, 0x2f, 0x36, 0xfb,
	0xab, 0x92, 0x3c, 0xe8, 0xd4, 0x51, 0x0f, 0xc8, 0xc0, 0xed, 0x65, 0x17, 0x39, 0x31, 0x49, 0x7c,
	0xae, 0x47, 0x7c, 0x01, 0x61, 0x2f, 0x1b, 0x21, 0xbb, 0xaa, 0x16, 0x91, 0x1b, 0x93, 0x64, 0xc6,
	0xa9, 0x35, 0x32, 0x81, 0x4f, 0xc1, 0xff, 0x79, 0x38, 0x5f, 0x64, 0xe4, 0x99, 0xc0, 0x0a, 0x7c,
	0x03, 0x61, 0xd3, 0x0a, 0x69, 0x99, 0xbe, 0x61, 0xe2, 0x7f, 0x66, 0xde, 0x0a, 0x69, 0xa0, 0xb4,
	0xb9, 0x4d, 0x9a, 0x71, 0x6e, 0xdb, 0xd3, 0x45, 0x69, 0xc6, 0xd4, 0x32, 0xac, 0x91, 0x89, 0xf1,
	0x02, 0x2a, 0x0a, 0x62, 0x92, 0x84, 0xff, 0x16, 0x50, 0xf8, 0x0c, 0x68, 0xfb, 0xab, 0xb1, 0x19,
	0x35, 0x59, 0x60, 0x74, 0xa6, 0x30, 0x01, 0xff, 0x74, 0xae, 0xfb, 0x21, 0x0a, 0x63, 0x37, 0x79,
	0x32, 0xde, 0xe0, 0xd4, 0xc8, 0x43, 0x27, 0xfb, 0x81, 0xdb, 0xc2, 0xf3, 0x57, 0x40, 0xef, 0x16,
	0x2e, 0xc0, 0xa9, 0x85, 0x39, 0xd4, 0x8c, 0x3b, 0xb5, 0x30, 0x5a, 0x99, 0x7b, 0x68, 0xad, 0x56,
	0x2f, 0x81, 0xde, 0x3f, 0x00, 0x43, 0xf0, 0x77, 0xdf, 0xf2, 0x94, 0xb3, 0x09, 0x52, 0xf0, 0xf2,
	0xdd, 0x36, 0x65, 0x64, 0xf5, 0x87, 0x40, 0x70, 0x3b, 0x2b, 0xce, 0x80, 0x16, 0x59, 0xfe, 0xb1,
	0xe2, 0xe9, 0x67, 0x36, 0x19, 0xa9, 0x92, 0x11, 0x9c, 0x43, 0x58, 0xee, 0x77, 0x3c, 0x35, 0xa1,
	0x33, 0x96, 0x25, 0x73, 0x71, 0x09, 0xf3, 0x0f, 0x59, 0xbe, 0xad, 0xf4, 0x4b, 0x4d, 0xc3, 0x7b,
	0x68, 0x95, 0xcc, 0x47, 0x84, 0x85, 0xb1, 0xbe, 0xbe, 0xff, 0xf4, 0xc5, 0xd6, 0xa6, 0x8f, 0xbc,
	0x92, 0x05, 0xdf, 0xa7, 0xe6, 0xc7, 0x78, 0xf7, 0x37, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x98, 0x36,
	0x66, 0x25, 0x02, 0x00, 0x00,
}
