version: "3"
services:
  kademliaBootstrap:
    image: kadlab:latest
    command: ["./d7024e"]
    ports:
      - "8080:8080" #map to port at server
    #networks:
    #    - kademlia_network

  kademliaNodes:
    image: kadlab:latest
    command: ["./d7024e", "-m", "client"]
    #networks:
    #    - kademlia_network

#networks:
#  kademlia_network: