GET http://localhost:8080/file/77ff0a3a0ec73e10ff408ece8728f84ae1af7bbf HTTP/1.1
content-type: application/json

###

POST http://localhost:8080/file HTTP/1.1
content-type: application/json

{
    "data": "THIS FILE IS AWESOME"
}

###

PATCH http://localhost:8080/file/anawesomeid HTTP/1.1
Content-Type: application/json

{
    "PinType": "pin"
}
